spring.application.name=ApiPanaderia

spring.mongodb.uri=mongodb+srv://carlos:sistemas307@cluster0.z2mwhx4.mongodb.net/?appName=Cluster0
spring.mongodb.database=apiPanaderia

# Puerto del servidor
server.port=${PORT:8080}
